### ISSUE TITLE
Quiz preparing

### ISSUE THREAD

**Issue by Dabrytskaya** [Moamin-AbuEwaida/architecture-starter-HYF-Group-1#5]
- [x] finding questions for the quiz about JS
- [x] finding correct and incorrect answers  for JS quiz
- [x] add questions file to the repo
- [x] add questions to data.js

**Comment by Moamin-AbuEwaida** [comment]
* [ ]  add questions to html file
> do we need to have the question into the HTML , i think we should have them into an array of objects in the data.js file

**Comment by Dabrytskaya** [comment]
> * [ ]   add questions to html file
> 
> > do we need to have the question into the HTML , i think we should have them into an array of objects in the data.js file

@Moamin-AbuEwaida I dont know exactly because I saw that they put them to html in one video. But in our case yes, I think data.js is correct.  :)
